//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODUL3_KEL31
{
    public partial class OrganisasiManagement
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblTotalMahasiswa;
        protected global::System.Web.UI.WebControls.Label lblTotalBidang;

        protected global::System.Web.UI.WebControls.TextBox txtNIM;
        protected global::System.Web.UI.WebControls.TextBox txtNama;
        protected global::System.Web.UI.WebControls.TextBox txtAngkatan;
        protected global::System.Web.UI.WebControls.TextBox txtJabatan;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.DropDownList ddlBidang;

        protected global::System.Web.UI.WebControls.Button btnSimpan;
        protected global::System.Web.UI.WebControls.Label lblPesan;

        protected global::System.Web.UI.WebControls.GridView gvMahasiswa;
    }
}
